CREATE OR REPLACE FUNCTION SG_CALC_INCOME_TAX (
    P_REGIME         VARCHAR2,
    P_TAXABLE_INCOME IN NUMBER
) RETURN NUMBER AS

    LN_INCOME_TAX           NUMBER;
    LN_INCOME               NUMBER;
    LN_DEDUCTION            NUMBER;
    LN_TAXABLE_INCOME       NUMBER;
    LN_TAX_EXEMTION_INCOOME NUMBER;
    LN_SLAB1_LOWER          NUMBER;
    LN_SLAB1_UPPER          NUMBER;
    LN_SLAB1_TAX_PERC       NUMBER;
    LN_SLAB1_TAX            NUMBER;
    LN_SLAB2_LOWER          NUMBER;
    LN_SLAB2_UPPER          NUMBER;
    LN_SLAB2_TAX_PERC       NUMBER;
    LN_SLAB2_TAX            NUMBER;
    LN_SLAB3_LOWER          NUMBER;
    LN_SLAB3_UPPER          NUMBER;
    LN_SLAB3_TAX_PERC       NUMBER;
    LN_SLAB3_TAX            NUMBER;
    LN_SLAB4_LOWER          NUMBER;
    LN_SLAB4_UPPER          NUMBER;
    LN_SLAB4_TAX_PERC       NUMBER;
    LN_SLAB4_TAX            NUMBER;
    LN_SLAB5_LOWER          NUMBER;
    LN_SLAB5_UPPER          NUMBER;
    LN_SLAB5_TAX_PERC       NUMBER;
    LN_SLAB5_TAX            NUMBER;
    LN_SLAB6_LOWER          NUMBER;
    LN_SLAB6_UPPER          NUMBER;
    LN_SLAB6_TAX_PERC       NUMBER;
    LN_SLAB6_TAX            NUMBER;
    LN_SLAB7_LOWER          NUMBER;
    LN_SLAB7_TAX_PERC       NUMBER;
    LN_SLAB7_TAX            NUMBER;
BEGIN
    APEX_DEBUG.ENTER('sg_calc_income_tax', 'p_taxable_income=%0', P_TAXABLE_INCOME);
    IF P_REGIME = 'NEW' THEN
        LN_TAX_EXEMTION_INCOOME := 1200000;
        LN_SLAB1_LOWER := 0;
        LN_SLAB1_UPPER := 400000;
        LN_SLAB1_TAX_PERC := 0;
        LN_SLAB2_LOWER := 400000;
        LN_SLAB2_UPPER := 800000;
        LN_SLAB2_TAX_PERC := 5;
        LN_SLAB3_LOWER := 800000;
        LN_SLAB3_UPPER := 1200000;
        LN_SLAB3_TAX_PERC := 10;
        LN_SLAB4_LOWER := 1200000;
        LN_SLAB4_UPPER := 1600000;
        LN_SLAB4_TAX_PERC := 15;
        LN_SLAB5_LOWER := 1600000;
        LN_SLAB5_UPPER := 2000000;
        LN_SLAB5_TAX_PERC := 20;
        LN_SLAB6_LOWER := 2000000;
        LN_SLAB6_UPPER := 2400000;
        LN_SLAB6_TAX_PERC := 25;
        LN_SLAB7_LOWER := 2400000;
        LN_SLAB7_TAX_PERC := 30;
        IF P_TAXABLE_INCOME > LN_TAX_EXEMTION_INCOOME THEN
            IF (
                P_TAXABLE_INCOME > LN_SLAB4_LOWER
                AND P_TAXABLE_INCOME < LN_SLAB4_UPPER
            ) THEN
                LN_SLAB1_TAX := ( LN_SLAB1_UPPER - LN_SLAB1_LOWER ) * LN_SLAB1_TAX_PERC / 100;
                LN_SLAB2_TAX := ( LN_SLAB2_UPPER - LN_SLAB2_LOWER ) * LN_SLAB2_TAX_PERC / 100;
                LN_SLAB3_TAX := ( LN_SLAB3_UPPER - LN_SLAB3_LOWER ) * LN_SLAB3_TAX_PERC / 100;
                LN_SLAB4_TAX := ( P_TAXABLE_INCOME - LN_SLAB4_LOWER ) * LN_SLAB4_TAX_PERC / 100;
                LN_INCOME_TAX := LN_SLAB1_TAX + LN_SLAB2_TAX + LN_SLAB3_TAX + LN_SLAB4_TAX;
            ELSIF (
                P_TAXABLE_INCOME > LN_SLAB5_LOWER
                AND P_TAXABLE_INCOME < LN_SLAB5_UPPER
            ) THEN
                LN_SLAB1_TAX := ( LN_SLAB1_UPPER - LN_SLAB1_LOWER ) * LN_SLAB1_TAX_PERC / 100;
                LN_SLAB2_TAX := ( LN_SLAB2_UPPER - LN_SLAB2_LOWER ) * LN_SLAB2_TAX_PERC / 100;
                LN_SLAB3_TAX := ( LN_SLAB3_UPPER - LN_SLAB3_LOWER ) * LN_SLAB3_TAX_PERC / 100;
                LN_SLAB4_TAX := ( LN_SLAB4_UPPER - LN_SLAB4_LOWER ) * LN_SLAB4_TAX_PERC / 100;
                LN_SLAB5_TAX := ( P_TAXABLE_INCOME - LN_SLAB5_LOWER ) * LN_SLAB5_TAX_PERC / 100;
                LN_INCOME_TAX := LN_SLAB1_TAX + LN_SLAB2_TAX + LN_SLAB3_TAX + LN_SLAB4_TAX + LN_SLAB5_TAX;
            ELSIF (
                P_TAXABLE_INCOME > LN_SLAB6_LOWER
                AND P_TAXABLE_INCOME < LN_SLAB6_UPPER
            ) THEN
                LN_SLAB1_TAX := ( LN_SLAB1_UPPER - LN_SLAB1_LOWER ) * LN_SLAB1_TAX_PERC / 100;
                LN_SLAB2_TAX := ( LN_SLAB2_UPPER - LN_SLAB2_LOWER ) * LN_SLAB2_TAX_PERC / 100;
                LN_SLAB3_TAX := ( LN_SLAB3_UPPER - LN_SLAB3_LOWER ) * LN_SLAB3_TAX_PERC / 100;
                LN_SLAB4_TAX := ( LN_SLAB4_UPPER - LN_SLAB4_LOWER ) * LN_SLAB4_TAX_PERC / 100;
                LN_SLAB5_TAX := ( LN_SLAB5_UPPER - LN_SLAB5_LOWER ) * LN_SLAB5_TAX_PERC / 100;
                LN_SLAB6_TAX := ( P_TAXABLE_INCOME - LN_SLAB6_LOWER ) * LN_SLAB6_TAX_PERC / 100;
                LN_INCOME_TAX := LN_SLAB1_TAX + LN_SLAB2_TAX + LN_SLAB3_TAX + LN_SLAB4_TAX + LN_SLAB5_TAX + LN_SLAB6_TAX;
            ELSIF P_TAXABLE_INCOME > LN_SLAB7_LOWER THEN
                LN_SLAB1_TAX := ( LN_SLAB1_UPPER - LN_SLAB1_LOWER ) * LN_SLAB1_TAX_PERC / 100;
                LN_SLAB2_TAX := ( LN_SLAB2_UPPER - LN_SLAB2_LOWER ) * LN_SLAB2_TAX_PERC / 100;
                LN_SLAB3_TAX := ( LN_SLAB3_UPPER - LN_SLAB3_LOWER ) * LN_SLAB3_TAX_PERC / 100;
                LN_SLAB4_TAX := ( LN_SLAB4_UPPER - LN_SLAB4_LOWER ) * LN_SLAB4_TAX_PERC / 100;
                LN_SLAB5_TAX := ( LN_SLAB5_UPPER - LN_SLAB5_LOWER ) * LN_SLAB5_TAX_PERC / 100;
                LN_SLAB6_TAX := ( LN_SLAB6_UPPER - LN_SLAB6_LOWER ) * LN_SLAB6_TAX_PERC / 100;
                LN_SLAB7_TAX := ( P_TAXABLE_INCOME - LN_SLAB7_LOWER ) * LN_SLAB7_TAX_PERC / 100;
                LN_INCOME_TAX := LN_SLAB1_TAX + LN_SLAB2_TAX + LN_SLAB3_TAX + LN_SLAB4_TAX + LN_SLAB5_TAX + LN_SLAB6_TAX + LN_SLAB7_TAX
                ;
            END IF;
        ELSE
            LN_INCOME_TAX := 0;
        END IF;

    ELSE
        LN_SLAB1_LOWER := 0;
        LN_SLAB1_UPPER := 250000;
        LN_SLAB1_TAX_PERC := 0;
        LN_SLAB2_LOWER := 250000;
        LN_SLAB2_UPPER := 500000;
        LN_SLAB2_TAX_PERC := 5;
        LN_SLAB3_LOWER := 500000;
        LN_SLAB3_UPPER := 1000000;
        LN_SLAB3_TAX_PERC := 20;
        LN_SLAB4_LOWER := 1000000;
        LN_SLAB4_TAX_PERC := 30;
        IF (
            P_TAXABLE_INCOME > LN_SLAB2_LOWER
            AND P_TAXABLE_INCOME < LN_SLAB2_UPPER
        ) THEN
            LN_SLAB2_TAX := ( P_TAXABLE_INCOME - LN_SLAB2_LOWER ) * LN_SLAB2_TAX_PERC / 100;
            LN_INCOME_TAX := LN_SLAB2_TAX;
        ELSIF (
            P_TAXABLE_INCOME > LN_SLAB3_LOWER
            AND P_TAXABLE_INCOME < LN_SLAB3_UPPER
        ) THEN
            LN_SLAB2_TAX := ( LN_SLAB2_UPPER - LN_SLAB2_LOWER ) * LN_SLAB2_TAX_PERC / 100;
            LN_SLAB3_TAX := ( P_TAXABLE_INCOME - LN_SLAB3_LOWER ) * LN_SLAB3_TAX_PERC / 100;
            LN_INCOME_TAX := LN_SLAB2_TAX + LN_SLAB3_TAX;
        ELSIF P_TAXABLE_INCOME > LN_SLAB4_LOWER THEN
            LN_SLAB2_TAX := ( LN_SLAB2_UPPER - LN_SLAB2_LOWER ) * LN_SLAB2_TAX_PERC / 100;
            LN_SLAB3_TAX := ( LN_SLAB3_UPPER - LN_SLAB3_LOWER ) * LN_SLAB3_TAX_PERC / 100;
            LN_SLAB4_TAX := ( P_TAXABLE_INCOME - LN_SLAB4_LOWER ) * LN_SLAB4_TAX_PERC / 100;
            LN_INCOME_TAX := LN_SLAB2_TAX + LN_SLAB3_TAX + LN_SLAB4_TAX;
        ELSE
            LN_INCOME_TAX := 0;
        END IF;

    END IF;

    RETURN LN_INCOME_TAX;
EXCEPTION
    WHEN OTHERS THEN
        APEX_DEBUG.WARN(
            P_MESSAGE => 'Unexpected error. ',
            P0        => SQLERRM
        );
        RAISE;
END SG_CALC_INCOME_TAX;